name: tutorials

on:
  push:
    branches: [master,dev,paparazzi]
  pull_request:
    branches: [master]

jobs:
  notebooks:
    name: "${{ matrix.pymc-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pymc-version: "3.11"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ~/.theano
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.pymc-version }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pymc3==${{ matrix.pymc-version }} pymc3-ext sympy corner batman-package jupyter
          python -m pip install -e ".[docs]"

      - name: Set up environment
        shell: bash -l {0}
        run: |
          jupyter nbextension enable --py widgetsnbextension

      - name: Execute notebooks
        shell: bash -l {0}
        run: |
          cd notebooks
          python run_notebooks.py

      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: notebooks

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1.0.0
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
